# Generated by Django 2.2.13 on 2020-12-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('isin', models.CharField(help_text='International Securities Identification Number', max_length=12, primary_key=True, serialize=False)),
                ('size', models.IntegerField(help_text='Size of offering')),
                ('currency', models.CharField(help_text='Currency of offering in ISO 4217 code format', max_length=3)),
                ('maturity', models.DateField(auto_now=True, help_text='Date of maturity')),
                ('lei', models.CharField(help_text='Legal Entity Field', max_length=20)),
            ],
        ),
    ]
