# Generated by Django 2.2.13 on 2021-01-01 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_bond_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of data', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
